version: "3.3"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile.prod
    command: ./bin/start.prod.sh
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    networks:
      main:
        aliases:
          - web

  web_proxy:
    container_name: web_proxy
    build:
      dockerfile: Dockerfile.web_proxy
    command: ./start.web_proxy.sh
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      main:
        aliases:
          - web_proxy

networks:
  main: