version: "3.3"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile.prod
    command: ./bin/start.prod.sh
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - .env.prod