version: "3.8"

services:
  gunicorn:
    container_name: gunicorn
    build:
      dockerfile: Dockerfile.gunicorn
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.gunicorn
    networks:
      main:
        aliases:
          - gunicorn

  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    networks:
      main:
        aliases:
          - proxy
    depends_on:
      - gunicorn
    environment:
      - DJANGO_HOST=gunicorn
      - DJANGO_PORT=8000

networks:
  main: