version: "3.3"

services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile.prod
    command: [ "./bin/start.gunicorn.sh" ]
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    networks:
      main:
        aliases:
          - web

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx
    command: [ "./start.nginx.sh" ]
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      main:
        aliases:
          - nginx

networks:
  main: