version: "3.3"

services:
  web:
    container_name: web
    build: .
    command: ./bin/start.dev.sh
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "3434:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev.db

volumes:
  postgres_data: