version: "3.3"

services:
  web:
    container_name: web
    build: .
    command: ./start.vger.sh
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env.vger
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.vger.db

volumes:
  postgres_data: